---


- name: VERIFY IF SSH TIME-OUT IS CONFIG'ED ON DEVICES
  hosts: All_IOSdevices
  # hosts: static_test
  connection: network_cli
  serial: 1
  gather_facts: no


  tasks:

    - name: PLAY 01 --- VERIFY IF "IP SSH TIME-OUT" CMD WAS CONFIG'ED
      ios_command:
      
        commands:
          - sh run | in ip ssh time-out
      ignore_errors: yes
      register: results
          
    - name: PLAY 02 --- SAVE THE HOSTNAMES OF THE DEVICES WITH MT LIST TO FILE
      lineinfile:
        line: "{{ inventory_hostname }}"
        path: "{{ playbook_dir }}/No-SSH-Config"
        create: yes
      
      when: results.stdout[0] == ""
      ignore_errors: yes
      # with_items: "{{ SerialNum }}"

# msg": "FCW2220A6B8 belongs to ADM-ALEXK-2960L-18"

    
      # with_items: "{{ ansible_net_model | dict2items }}"
      # when: item.value.operstatus == 'down'
    # - debug:
    #      var: ansible_net_model

    # - name: PLAY TEST --- DISPLAY RESULTS
    #   debug:
    #     var: results.stdout